import { AudioTrack } from "../types/audio";

// Authentic Islamic Audio Track Collections for Salah, Duas, and Hadith

export const SALAH_AUDIO_TRACKS: AudioTrack[] = [
  {
    id: "salah_takbeer",
    titleEn: "1. Takbeer (Takbeer-e-Tahreema)",
    titleUr: "۱. تکبیر تحریمہ",
    categoryEn: "Learn Salah",
    categoryUr: "نماز سیکھیں",
    arabicText: "اللَّهُ أَكْبَرُ",
    transliteration: "Allahu Akbar",
    translationEn: "Allah is the Greatest.",
    translationUr: "اللہ سب سے بڑا ہے۔",
    audioUrl: "https://everydayduas.com/audio/salah_takbeer.mp3",
    fallbackText: "الله أكبر",
    iconEmoji: "🙌",
    visualEmoji: "🙌",
    sectionType: "salah"
  },
  {
    id: "salah_sana",
    titleEn: "2. Sana (Opening Supplication)",
    titleUr: "۲. ثناء (دعائے استفتاح)",
    categoryEn: "Learn Salah",
    categoryUr: "نماز سیکھیں",
    arabicText: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَىٰ جَدُّكَ وَلَا إِلَٰهَ غَيْرُكَ",
    transliteration: "Subhanakal-lahumma wa bihamdika wa tabarakasmuka wa ta'ala jadduka wa la ilaha ghayruk",
    translationEn: "Glory be to You, O Allah, and praise. Blessed is Your Name, exalted is Your Majesty, and there is no god but You.",
    translationUr: "پاک ہے تو اے اللہ! اپنی تعریفوں کے ساتھ، اور مبارک ہے تیرا نام، اور بلند ہے تیری شان، اور تیرے سوا کوئی معبود نہیں ہے۔",
    audioUrl: "https://everydayduas.com/audio/salah_sana.mp3",
    fallbackText: "سبحانك اللهم وبحمدك وتبارك اسمك وتعالى جدك ولا إله غيرك",
    iconEmoji: "✨",
    visualEmoji: "🤲",
    sectionType: "salah"
  },
  {
    id: "salah_taawwudh",
    titleEn: "3. Ta'awwudh (Seeking Protection)",
    titleUr: "۳. تعوذ (تعوذ باللہ)",
    categoryEn: "Learn Salah",
    categoryUr: "نماز سیکھیں",
    arabicText: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
    transliteration: "A'udhu billahi minash-shaitanir-rajeem",
    translationEn: "I seek refuge in Allah from Satan, the rejected.",
    translationUr: "میں شیطان مردود سے اللہ کی پناہ مانگتا ہوں/مانگتی ہوں۔",
    audioUrl: "https://everydayduas.com/audio/salah_taawwudh.mp3",
    fallbackText: "أعوذ بالله من الشيطان الرجيم",
    iconEmoji: "🛡️",
    visualEmoji: "🧍",
    sectionType: "salah"
  },
  {
    id: "salah_tasmiyah",
    titleEn: "4. Tasmiyah (Bismillah)",
    titleUr: "۴. تسمیہ (بسم اللہ)",
    categoryEn: "Learn Salah",
    categoryUr: "نماز سیکھیں",
    arabicText: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    transliteration: "Bismillahir-Rahmanir-Rahim",
    translationEn: "In the name of Allah, the Most Gracious, the Most Merciful.",
    translationUr: "اللہ کے نام سے شروع جو بڑا مہربان، نہایت رحم کرنے والا ہے۔",
    audioUrl: "https://everydayduas.com/audio/salah_tasmiyah.mp3",
    fallbackText: "بسم الله الرحمن الرحيم",
    iconEmoji: "🌹",
    visualEmoji: "📖",
    sectionType: "salah"
  },
  {
    id: "salah_fatihah",
    titleEn: "5. Surah Al-Fatihah",
    titleUr: "۵. سورۃ الفاتحہ",
    categoryEn: "Learn Salah",
    categoryUr: "نماز سیکھیں",
    arabicText: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ • الرَّحْمَٰنِ الرَّحِيمِ • مَالِكِ يَوْمِ الدِّينِ • إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ • اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ • صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
    transliteration: "Alhamdu lillahi Rabbil-'alamin. Ar-Rahmanir-Rahim. Maliki Yawmid-Deen. Iyyaka na'budu wa iyyaka nasta'een...",
    translationEn: "All praise is for Allah, Lord of the worlds. The Most Gracious, the Most Merciful. Master of the Day of Judgment...",
    translationUr: "تمام تعریفیں اللہ ہی کے لیے ہیں جو تمام جہانوں کا پالنے والا ہے، بڑا مہربان نہایت رحم کرنے والا ہے...",
    audioUrl: "https://everydayduas.com/audio/salah_fatihah.mp3",
    fallbackText: "الحمد لله رب العالمين الرحمن الرحيم مالك يوم الدين إياك نعبد وإياك نستعين اهدنا الصراط المستقيم صراط الذين أنعمت عليهم غير المغضوب عليهم ولا الضالين",
    iconEmoji: "📖",
    visualEmoji: "🧍",
    sectionType: "salah"
  },
  {
    id: "salah_short_surah",
    titleEn: "6. Short Surah (Surah Al-Ikhlas)",
    titleUr: "۶. سورۃ الاخلاص",
    categoryEn: "Learn Salah",
    categoryUr: "نماز سیکھیں",
    arabicText: "قُلْ هُوَ اللَّهُ أَحَدٌ • اللَّهُ الصَّمَدُ • لَمْ يَلِدْ وَلَمْ يُولَدْ • وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
    transliteration: "Qul Huwallahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad",
    translationEn: "Say: He is Allah, [who is] One. Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent.",
    translationUr: "کہہ دیجیے: وہ اللہ ایک ہے۔ اللہ بے نیاز ہے۔ نہ اس کی کوئی اولاد ہے اور نہ وہ کسی کی اولاد ہے اور نہ کوئی اس کا ہمسر ہے۔",
    audioUrl: "https://everydayduas.com/audio/salah_short_surah.mp3",
    fallbackText: "قل هو الله أحد ، الله الصمد ، لم يلد ولم يولد ، ولم يكن له كفوا أحد",
    iconEmoji: "💎",
    visualEmoji: "🧍",
    sectionType: "salah"
  },
  {
    id: "salah_ruku",
    titleEn: "7. Ruku Dhikr (Bowing Down)",
    titleUr: "۷. رکوع کی تسبیح",
    categoryEn: "Learn Salah",
    categoryUr: "نماز سیکھیں",
    arabicText: "سُبْحَانَ رَبِّيَ الْعَظِيمِ • سُبْحَانَ رَبِّيَ الْعَظِيمِ • سُبْحَانَ رَبِّيَ الْعَظِيمِ",
    transliteration: "Subhana Rabbiyal-'Azeem (3 times)",
    translationEn: "Glory be to my Lord, the Most Magnificent (3 times).",
    translationUr: "پاک ہے میرا رب عظمت والا (تین بار)۔",
    audioUrl: "https://everydayduas.com/audio/salah_ruku.mp3",
    fallbackText: "سبحان ربي العظيم ، سبحان ربي العظيم ، سبحان ربي العظيم",
    iconEmoji: "📐",
    visualEmoji: "🙇",
    sectionType: "salah"
  },
  {
    id: "salah_qawmah",
    titleEn: "8. Qawmah Dhikr (Standing from Ruku)",
    titleUr: "۸. قومہ کی دعا",
    categoryEn: "Learn Salah",
    categoryUr: "نماز سیکھیں",
    arabicText: "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ • رَبَّنَا وَلَكَ الْحَمْدُ",
    transliteration: "Sami'al-lahu liman hamidah • Rabbana wa lakal-hamd",
    translationEn: "Allah hears whoever praises Him. Our Lord, to You belongs all praise.",
    translationUr: "اللہ نے اس کی سن لی جس نے اس کی تعریف کی۔ اے ہمارے رب! تمام تعریفیں تیرے ہی لیے ہیں۔",
    audioUrl: "https://everydayduas.com/audio/salah_qawmah.mp3",
    fallbackText: "سمع الله لمن حمده ، ربنا ولك الحمد",
    iconEmoji: "✨",
    visualEmoji: "🧍",
    sectionType: "salah"
  },
  {
    id: "salah_sujood",
    titleEn: "9. Sujood Dhikr (Prostration)",
    titleUr: "۹. سجدے کی تسبیح",
    categoryEn: "Learn Salah",
    categoryUr: "نماز سیکھیں",
    arabicText: "سُبْحَانَ رَبِّيَ الْأَعْلَىٰ • سُبْحَانَ رَبِّيَ الْأَعْلَىٰ • سُبْحَانَ رَبِّيَ الْأَعْلَىٰ",
    transliteration: "Subhana Rabbiyal-A'laa (3 times)",
    translationEn: "Glory be to my Lord, the Most High (3 times).",
    translationUr: "پاک ہے میرا رب جو سب سے بلند تر ہے (تین بار)۔",
    audioUrl: "https://everydayduas.com/audio/salah_sujood.mp3",
    fallbackText: "سبحان ربي الأعلى ، سبحان ربي الأعلى ، سبحان ربي الأعلى",
    iconEmoji: "💖",
    visualEmoji: "🧎",
    sectionType: "salah"
  },
  {
    id: "salah_jalsa",
    titleEn: "10. Jalsa Dhikr (Between Prostrations)",
    titleUr: "۱۰. جلسہ کی دعا",
    categoryEn: "Learn Salah",
    categoryUr: "نماز سیکھیں",
    arabicText: "رَبِّ اغْفِرْ لِي • رَبِّ اغْفِرْ لِي",
    transliteration: "Rabbighfir li, Rabbighfir li",
    translationEn: "O my Lord, forgive me. O my Lord, forgive me.",
    translationUr: "اے میرے رب! مجھے معاف فرما، اے میرے رب! مجھے معاف فرما۔",
    audioUrl: "https://everydayduas.com/audio/salah_jalsa.mp3",
    fallbackText: "رب اغفر لي ، رب اغفر لي",
    iconEmoji: "📿",
    visualEmoji: "🧎‍♂️",
    sectionType: "salah"
  },
  {
    id: "salah_tashahhud",
    titleEn: "11. Tashahhud (Attahiyyat)",
    titleUr: "۱۱. التحیات (تشہد)",
    categoryEn: "Learn Salah",
    categoryUr: "نماز سیکھیں",
    arabicText: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ • السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ • السَّلَامُ عَلَيْنَا وَعَلَىٰ عِبَادِ اللَّهِ الصَّالِحِينَ • أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
    transliteration: "At-tahiyyatu lillahi was-salawatu wat-tayyibat...",
    translationEn: "All compliments, prayers, and pure words are due to Allah. Peace be upon you O Prophet...",
    translationUr: "تمام قولی، بدنی اور مالی عبادتیں اللہ ہی کے لیے ہیں۔ اے نبی! آپ پر سلام اور اللہ کی رحمت اور برکتیں ہوں...",
    audioUrl: "https://everydayduas.com/audio/salah_tashahhud.mp3",
    fallbackText: "التحيات لله والصلوات والطيبات ، السلام عليك أيها النبي ورحمة الله وبركاته ، السلام علينا وعلى عباد الله الصالحين ، أشهد أن لا إله إلا الله وأشهد أن محمدا عبده ورسوله",
    iconEmoji: "🤲",
    visualEmoji: "🧎‍♂️",
    sectionType: "salah"
  },
  {
    id: "salah_durood",
    titleEn: "12. Durood Ibrahim",
    titleUr: "۱۲. درودِ ابراہیمی",
    categoryEn: "Learn Salah",
    categoryUr: "نماز سیکھیں",
    arabicText: "اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ • اللَّهُمَّ بَارِكْ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ",
    transliteration: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammadin...",
    translationEn: "O Allah, send peace and blessings upon Muhammad and the family of Muhammad...",
    translationUr: "اے اللہ! محمد (صلی اللہ علیہ وسلم) اور ان کی آل پر رحمت نازل فرما...",
    audioUrl: "https://everydayduas.com/audio/salah_durood.mp3",
    fallbackText: "اللهم صل على محمد وعلى آل محمد كما صليت على إبراهيم وعلى آل إبراهيم إنك حميد مجيد ، اللهم بارك على محمد وعلى آل محمد كما باركت على إبراهيم وعلى آل إبراهيم إنك حميد مجيد",
    iconEmoji: "🌹",
    visualEmoji: "📿",
    sectionType: "salah"
  },
  {
    id: "salah_dua_after_durood",
    titleEn: "13. Dua After Durood",
    titleUr: "۱۳. درود کے بعد کی دعا",
    categoryEn: "Learn Salah",
    categoryUr: "نماز سیکھیں",
    arabicText: "رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي رَبَّنَا وَتَقَبَّلْ دُعَاءِ • رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ",
    transliteration: "Rabbij'alni muqeemas-salati wa min dhurriyyati Rabbana wa taqabbal du'a...",
    translationEn: "My Lord, make me an establisher of prayer, and from my descendants. Our Lord, and accept my supplication...",
    translationUr: "اے میرے رب! مجھے اور میری اولاد کو نماز قائم کرنے والا بنا، اے ہمارے رب! اور میری دعا قبول فرما...",
    audioUrl: "https://everydayduas.com/audio/salah_dua_after_durood.mp3",
    fallbackText: "رب اجعلني مقيم الصلاة ومن ذريتي ربنا وتقبل دعاء ، ربنا اغفر لي ولوالدي وللمؤمنين يوم يقوم الحساب",
    iconEmoji: "🕊️",
    visualEmoji: "🤲",
    sectionType: "salah"
  },
  {
    id: "salah_salam",
    titleEn: "14. Tasleem (Salam to Right & Left)",
    titleUr: "۱۴. سلام پھیرنا",
    categoryEn: "Learn Salah",
    categoryUr: "نماز سیکھیں",
    arabicText: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ • السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ",
    transliteration: "Assalamu 'alaikum wa rahmatullah (Right & Left)",
    translationEn: "Peace and mercy of Allah be upon you.",
    translationUr: "تم پر سلامتی اور اللہ کی رحمت ہو۔",
    audioUrl: "https://everydayduas.com/audio/salah_salam.mp3",
    fallbackText: "السلام عليكم ورحمة الله ، السلام عليكم ورحمة الله",
    iconEmoji: "🕊️",
    visualEmoji: "🙋‍♂️",
    sectionType: "salah"
  }
];

export const WUDU_AUDIO_TRACKS: AudioTrack[] = [
  {
    id: "wudu_step_1",
    titleEn: "1. Niyyah & Bismillah",
    titleUr: "۱. نیت اور بسم اللہ",
    categoryEn: "Wudu Steps",
    categoryUr: "وضو کا طریقہ",
    arabicText: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    transliteration: "Bismillahir-Rahmanir-Rahim",
    translationEn: "In the name of Allah, the Most Gracious, the Most Merciful.",
    translationUr: "اللہ کے نام سے شروع جو بڑا مہربان نہایت رحم کرنے والا ہے۔",
    audioUrl: "https://everydayduas.com/audio/wudu_step_1.mp3",
    fallbackText: "بسم الله الرحمن الرحيم",
    iconEmoji: "💧",
    visualEmoji: "🤲",
    sectionType: "salah"
  },
  {
    id: "wudu_step_2",
    titleEn: "2. Washing Hands 3 Times",
    titleUr: "۲. دونوں ہاتھ دھونا (تین بار)",
    categoryEn: "Wudu Steps",
    categoryUr: "وضو کا طریقہ",
    arabicText: "غَسْلُ الْيَدَيْنِ إِلَى الْكُفَّيْنِ ثَلَاثًا",
    transliteration: "Ghaslul-yadayni ilal-kuffayni thalathan",
    translationEn: "Wash both hands up to the wrists three times, making sure water passes between fingers.",
    translationUr: "دونوں ہاتھوں کو کلائیوں تک تین بار اچھی طرح دھوئیں۔",
    audioUrl: "https://everydayduas.com/audio/wudu_step_2.mp3",
    fallbackText: "غسل اليدين إلى الكفين ثلاثا",
    iconEmoji: "🧼",
    visualEmoji: "👐",
    sectionType: "salah"
  },
  {
    id: "wudu_step_3",
    titleEn: "3. Rinsing Mouth 3 Times",
    titleUr: "۳. کلی کرنا (تین بار)",
    categoryEn: "Wudu Steps",
    categoryUr: "وضو کا طریقہ",
    arabicText: "الْمَضْمَضَةُ ثَلَاثًا",
    transliteration: "Al-Madmadatu thalathan",
    translationEn: "Rinse the mouth thoroughly with water three times.",
    translationUr: "تین بار منہ میں پانی ڈال کر کلی کریں۔",
    audioUrl: "https://everydayduas.com/audio/wudu_step_3.mp3",
    fallbackText: "المضمضة ثلاثا",
    iconEmoji: "🥛",
    visualEmoji: "👄",
    sectionType: "salah"
  },
  {
    id: "wudu_step_4",
    titleEn: "4. Sniffing Water into Nose 3 Times",
    titleUr: "۴. ناک میں پانی ڈالنا (تین بار)",
    categoryEn: "Wudu Steps",
    categoryUr: "وضو کا طریقہ",
    arabicText: "الِاسْتِنْشَاقُ وَالِاسْتِنْثَارُ ثَلَاثًا",
    transliteration: "Al-Istinshaqu wal-Istintharu thalathan",
    translationEn: "Sniff water gently into the nose and blow it out three times.",
    translationUr: "تین بار ناک میں پانی چڑھا کر صاف کریں۔",
    audioUrl: "https://everydayduas.com/audio/wudu_step_4.mp3",
    fallbackText: "الاستنشاق والاستنثار ثلاثا",
    iconEmoji: "🌊",
    visualEmoji: "👃",
    sectionType: "salah"
  },
  {
    id: "wudu_step_5",
    titleEn: "5. Washing Face 3 Times",
    titleUr: "۵. چہرہ دھونا (تین بار)",
    categoryEn: "Wudu Steps",
    categoryUr: "وضو کا طریقہ",
    arabicText: "غَسْلُ الْوَجْهِ ثَلَاثًا",
    transliteration: "Ghaslul-wajhi thalathan",
    translationEn: "Wash the entire face from forehead to chin and ear to ear three times.",
    translationUr: "پیشانی کے بالوں سے لے کر ٹھوڑی کے نیچے تک اور ایک کان کی لو سے دوسرے کان تک پورا چہرہ دھوئیں۔",
    audioUrl: "https://everydayduas.com/audio/wudu_step_5.mp3",
    fallbackText: "غسل الوجه ثلاثا",
    iconEmoji: "✨",
    visualEmoji: "😊",
    sectionType: "salah"
  },
  {
    id: "wudu_step_6",
    titleEn: "6. Washing Arms to Elbows 3 Times",
    titleUr: "۶. کہنیوں تک ہاتھ دھونا (تین بار)",
    categoryEn: "Wudu Steps",
    categoryUr: "وضو کا طریقہ",
    arabicText: "غَسْلُ الْيَدَيْنِ إِلَى الْمِرْفَقَيْنِ ثَلَاثًا",
    transliteration: "Ghaslul-yadayni ilal-mirfaqayni thalathan",
    translationEn: "Wash the right arm including the elbow 3 times, then the left arm 3 times.",
    translationUr: "پہلے دائیں ہاتھ کو کہنی سمیت تین بار اور پھر بائیں ہاتھ کو کہنی سمیت تین بار دھوئیں۔",
    audioUrl: "https://everydayduas.com/audio/wudu_step_6.mp3",
    fallbackText: "غسل اليدين إلى المرفقين ثلاثا",
    iconEmoji: "💪",
    visualEmoji: "💪",
    sectionType: "salah"
  },
  {
    id: "wudu_step_7",
    titleEn: "7. Wiping Head & Ears (Masah Once)",
    titleUr: "۷. سر اور کانوں کا مسح کرنا",
    categoryEn: "Wudu Steps",
    categoryUr: "وضو کا طریقہ",
    arabicText: "مَسْحُ الرَّأْسِ وَالْأُذُنَيْنِ مَرَّةً وَاحِدَةً",
    transliteration: "Mas'hur-ra'si wal-udhunayni marratan wahidah",
    translationEn: "Wipe wet hands over the head from front to back and clean inside and back of ears once.",
    translationUr: "تر ہاتھوں سے پورے سر کا ایک بار مسح کریں اور کانوں کا مسح بھی کریں۔",
    audioUrl: "https://everydayduas.com/audio/wudu_step_7.mp3",
    fallbackText: "مسح الرأس والأذنين مرة واحدة",
    iconEmoji: "💆‍♂️",
    visualEmoji: "💆‍♂️",
    sectionType: "salah"
  },
  {
    id: "wudu_step_8",
    titleEn: "8. Washing Feet to Ankles 3 Times",
    titleUr: "۸. ٹخنوں تک پاؤں دھونا (تین بار)",
    categoryEn: "Wudu Steps",
    categoryUr: "وضو کا طریقہ",
    arabicText: "غَسْلُ الرِّجْلَيْنِ إِلَى الْكَعْبَيْنِ ثَلَاثًا",
    transliteration: "Ghaslur-rijlayni ilal-ka'bayni thalathan",
    translationEn: "Wash the right foot including ankles 3 times, then the left foot 3 times.",
    translationUr: "پہلے دایاں پاؤں ٹخنوں سمیت تین بار دھوئیں اور پھر بایاں پاؤں ٹخنوں سمیت تین بار دھوئیں۔",
    audioUrl: "https://everydayduas.com/audio/wudu_step_8.mp3",
    fallbackText: "غسل الرجلين إلى الكعبين ثلاثا",
    iconEmoji: "🦶",
    visualEmoji: "🦶",
    sectionType: "salah"
  },
  {
    id: "wudu_step_9",
    titleEn: "9. Dua After Completing Wudu",
    titleUr: "۹. وضو کے بعد کی دعا",
    categoryEn: "Wudu Steps",
    categoryUr: "وضو کا طریقہ",
    arabicText: "أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ • اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ",
    transliteration: "Ash-hadu alla ilaha illallahu wahdahu la sharika lahu wa ash-hadu anna Muhammadan 'abduhu wa rasuluh. Allahummaj'alni minat-tawwabina waj'alni minal-mutatahhiriin",
    translationEn: "I bear witness that there is no god but Allah alone without partner, and Muhammad is His servant and Messenger. O Allah, make me among those who repent and keep clean.",
    translationUr: "میں گواہی دیتا ہوں کہ اللہ کے سوا کوئی معبود نہیں وہ اکیلا ہے اس کا کوئی شریک نہیں اور محمد اس کے بندے اور رسول ہیں۔ اے اللہ! مجھے توبہ کرنے والوں اور پاک صاف رہنے والوں میں شامل فرما۔",
    audioUrl: "https://everydayduas.com/audio/wudu_step_9.mp3",
    fallbackText: "أشهد أن لا إله إلا الله وحده لا شريك له وأشهد أن محمدا عبده ورسوله ، اللهم اجعلني من التوابين واجعلني من المتطهرين",
    iconEmoji: "🤲",
    visualEmoji: "🌟",
    sectionType: "salah"
  }
];

export const DUA_AUDIO_TRACKS: AudioTrack[] = [
  {
    id: "dua_eat_before",
    titleEn: "Before Eating",
    titleUr: "کھانے سے پہلے کی دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "بِسْمِ اللَّهِ وَعَلَىٰ بَرَكَةِ اللَّهِ",
    transliteration: "Bismillaahi wa 'alaa barakatil-laah",
    translationEn: "In the name of Allah and upon the blessings of Allah.",
    translationUr: "اللہ کے نام کے ساتھ اور اللہ کی برکت پر (ہم نے کھانا شروع کیا)۔",
    audioUrl: "https://everydayduas.com/audio/dua_eat_before.mp3",
    fallbackText: "بسم الله وعلى بركة الله",
    iconEmoji: "🍎",
    sectionType: "dua"
  },
  {
    id: "dua_eat_after",
    titleEn: "After Eating",
    titleUr: "کھانا کھانے کے بعد کی دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
    transliteration: "Alhamdu lillaahil-lazii at'amanaa wa saqaanaa wa ja'alanaa Muslimiin",
    translationEn: "All praise is for Allah, who fed us, gave us drink, and made us Muslims.",
    translationUr: "سب تعریفیں اللہ کے لیے ہیں جس نے ہمیں کھلایا، پلایا اور مسلمان بنایا۔",
    audioUrl: "https://everydayduas.com/audio/dua_eat_after.mp3",
    fallbackText: "الحمد لله الذي أطعمنا وسقانا وجعلنا مسلمين",
    iconEmoji: "🥛",
    sectionType: "dua"
  },
  {
    id: "dua_sleep",
    titleEn: "Before Sleeping",
    titleUr: "سونے سے پہلے کی دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    transliteration: "Bismika Allahumma amuutu wa ahyaa",
    translationEn: "In Your name, O Allah, I die and I live.",
    translationUr: "اے اللہ! میں تیرے نام کے ساتھ مرتا ہوں (سوتا ہوں) اور جیتا (جاگتا) ہوں۔",
    audioUrl: "https://everydayduas.com/audio/dua_sleep.mp3",
    fallbackText: "باسمك اللهم أموت وأحيا",
    iconEmoji: "🌙",
    sectionType: "dua"
  },
  {
    id: "dua_wake",
    titleEn: "When Waking Up",
    titleUr: "سو کر اٹھنے کی دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    transliteration: "Alhamdu lillaahil-lazii ahyaanaa ba'da maa amaatanaa wa ilaihin-nushuur",
    translationEn: "All praise is for Allah, who gave us life after death, and to Him is the final return.",
    translationUr: "تمام تعریفیں اللہ ہی کے لیے ہیں جس نے ہمیں سلانے کے بعد دوبارہ جگایا اور اسی کی طرف لوٹنا ہے۔",
    audioUrl: "https://everydayduas.com/audio/dua_wake.mp3",
    fallbackText: "الحمد لله الذي أحيانا بعد ما أماتنا وإليه النشور",
    iconEmoji: "☀️",
    sectionType: "dua"
  },
  {
    id: "dua_parents",
    titleEn: "Dua for Parents",
    titleUr: "والدین کے لیے دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    transliteration: "Rabbi-rhamhumaa kamaa rabbayaanii saghiiraa",
    translationEn: "My Lord! Have mercy on them both, as they brought me up when I was little.",
    translationUr: "اے میرے رب! ان دونوں (والدین) پر رحم فرما جس طرح انہوں نے مجھے بچپن میں پالا۔",
    audioUrl: "https://everydayduas.com/audio/dua_parents.mp3",
    fallbackText: "رب ارحمهما كما ربياني صغيرا",
    iconEmoji: "💖",
    sectionType: "dua"
  },
  {
    id: "dua_mosque_enter",
    titleEn: "Entering the Mosque",
    titleUr: "مسجد میں داخل ہونے کی دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    transliteration: "Allahummaf-tah lii abwaaba rahmatik",
    translationEn: "O Allah, open for me the gates of Your mercy.",
    translationUr: "اے اللہ! میرے لیے اپنی رحمت کے دروازے کھول دے۔",
    audioUrl: "https://everydayduas.com/audio/dua_mosque_enter.mp3",
    fallbackText: "اللهم افتح لي أبواب رحمتك",
    iconEmoji: "🕌",
    sectionType: "dua"
  },
  {
    id: "dua_mosque_leave",
    titleEn: "Leaving the Mosque",
    titleUr: "مسجد سے نکلنے کی دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
    transliteration: "Allahumma inni as'aluka min fadlik",
    translationEn: "O Allah, I ask You of Your bounty.",
    translationUr: "اے اللہ! میں تجھ سے تیرے فضل کا سوال کرتا ہوں۔",
    audioUrl: "https://everydayduas.com/audio/dua_mosque_leave.mp3",
    fallbackText: "اللهم إني أسألك من فضلك",
    iconEmoji: "🕌",
    sectionType: "dua"
  },
  {
    id: "dua_knowledge",
    titleEn: "Dua for Increasing Knowledge",
    titleUr: "علم میں اضافے کی دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "رَبِّ زِدْنِي عِلْمًا",
    transliteration: "Rabbi zidnii 'ilmaa",
    translationEn: "O my Lord! Increase me in knowledge.",
    translationUr: "اے میرے رب! میرے علم میں اضافہ فرما۔",
    audioUrl: "https://everydayduas.com/audio/dua_knowledge.mp3",
    fallbackText: "رب زدني علما",
    iconEmoji: "📚",
    sectionType: "dua"
  },
  {
    id: "dua_protection",
    titleEn: "Dua for Protection",
    titleUr: "حفاظت اور عافیت کی دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    transliteration: "Bismillaahil-ladhii laa yadurru ma'as-mihii shai'un fil-ardi wa laa fis-samaa'i wa Huwas-Samii'ul-'Aliim",
    translationEn: "In the name of Allah with Whose name nothing can cause harm in the earth nor in the heavens, and He is the All-Hearing, All-Knowing.",
    translationUr: "اللہ کے نام کے ساتھ جس کے نام کی برکت سے زمین اور آسمان میں کوئی چیز نقصان نہیں پہنچا سکتی اور وہ خوب سننے والا، جاننے والا ہے۔",
    audioUrl: "https://everydayduas.com/audio/dua_protection.mp3",
    fallbackText: "بسم الله الذي لا يضر مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم",
    iconEmoji: "🛡️",
    sectionType: "dua"
  },
  {
    id: "dua_travel",
    titleEn: "Dua Before Traveling",
    titleUr: "سفر کی دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنْقَلِبُونَ",
    transliteration: "Subhanal-ladhii sakh-khara lanaa haadhaa wa maa kunnaa lahu muqriniina wa innaa ilaa Rabbinaa lamunqalibuun",
    translationEn: "Glory to Him Who has subjected this to us, and we could never have accomplished it by ourselves, and to our Lord we shall return.",
    translationUr: "پاک ہے وہ ذات جس نے اس سواری کو ہمارے تابع کر دیا حالانکہ ہم اس پر قابو پانے والے نہ تھے اور ہم اپنے رب کی طرف لوٹنے والے ہیں۔",
    audioUrl: "https://everydayduas.com/audio/dua_travel.mp3",
    fallbackText: "سبحان الذي سخر لنا هذا وما كنا له مقرنين وإنا إلى ربنا لمنقلبون",
    iconEmoji: "🚗",
    sectionType: "dua"
  },
  {
    id: "dua_sneeze",
    titleEn: "Dua After Sneezing",
    titleUr: "چھینکنے کے بعد کی دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "الْحَمْدُ لِلَّهِ",
    transliteration: "Alhamdulillah",
    translationEn: "All praise is due to Allah.",
    translationUr: "تمام تعریفیں اللہ ہی کے لیے ہیں۔",
    audioUrl: "https://everydayduas.com/audio/dua_sneeze.mp3",
    fallbackText: "الحمد لله",
    iconEmoji: "😊",
    sectionType: "dua"
  },
  {
    id: "dua_home_enter",
    titleEn: "Entering the Home",
    titleUr: "گھر میں داخل ہونے کی دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَىٰ اللَّهِ رَبِّنَا تَوَكَّلْنَا",
    transliteration: "Bismillaahi walajnaa wa bismillaahi kharajnaa wa 'alal-laahi Rabbinaa tawakkalnaa",
    translationEn: "In the name of Allah we enter, and in the name of Allah we leave, and upon our Lord we rely.",
    translationUr: "اللہ کے نام سے ہم داخل ہوئے اور اللہ کے نام سے ہم نکلے اور ہم نے اپنے رب پر بھروسہ کیا۔",
    audioUrl: "https://everydayduas.com/audio/dua_home_enter.mp3",
    fallbackText: "بسم الله ولجنا وبسم الله خرجنا وعلى الله ربنا توكلنا",
    iconEmoji: "🏡",
    sectionType: "dua"
  },
  {
    id: "dua_home_leave",
    titleEn: "Leaving the Home",
    titleUr: "گھر سے نکلنے کی دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transliteration: "Bismillaahi tawakkaltu 'alal-laah, wa laa hawla wa laa quwwata illaa billaah",
    translationEn: "In the name of Allah, I place my trust in Allah; there is no power or might except with Allah.",
    translationUr: "اللہ کے نام سے، میں نے اللہ پر بھروسہ کیا، اور گناہوں سے بچنے کی طاقت اور نیک کام کرنے کی توفیق صرف اللہ ہی کی طرف سے ہے۔",
    audioUrl: "https://everydayduas.com/audio/dua_home_leave.mp3",
    fallbackText: "بسم الله توكلت على الله ولا حول ولا قوة إلا بالله",
    iconEmoji: "🚶",
    sectionType: "dua"
  },
  {
    id: "dua_forgiveness",
    titleEn: "Dua for Forgiveness (Astaghfar)",
    titleUr: "استغفار کی دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
    transliteration: "Astaghfirullaahal-'Azeemalladhii laa ilaaha illaa Huwal-Hayyul-Qayyoomu wa atoobu ilaih",
    translationEn: "I seek forgiveness from Allah, the Magnificent, besides Whom there is no deity, the Ever-Living, the Sustainer, and I turn to Him in repentance.",
    translationUr: "میں عظمت والے اللہ سے معافی مانگتا ہوں جس کے سوا کوئی معبود نہیں، جو زندہ اور سب کو قائم رکھنے والا ہے اور میں اسی کی طرف توبہ کرتا ہوں۔",
    audioUrl: "https://everydayduas.com/audio/dua_forgiveness.mp3",
    fallbackText: "أستغفر الله العظيم الذي لا إله إلا هو الحي القيوم وأتوب إليه",
    iconEmoji: "🤲",
    sectionType: "dua"
  },
  {
    id: "dua_study",
    titleEn: "Dua Before Studying / Exams",
    titleUr: "سبق اور امتحان سے پہلے کی دعا",
    categoryEn: "Daily Duas",
    categoryUr: "روزمرہ دعائیں",
    arabicText: "اللَّهُمَّ لاَ سَهْلَ إِلاَّ مَا جَعَلْتَهُ سَهْلاً وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلاً",
    transliteration: "Allahumma laa sahla illaa maa ja'altahu sahlaa, wa Anta taj'alul-hazna idhaa shi'ta sahlaa",
    translationEn: "O Allah, there is no ease except in that which You have made easy, and You make the difficult easy if You wish.",
    translationUr: "اے اللہ! کوئی کام آسان نہیں مگر وہی جسے تو آسان بنا دے، اور تو جب چاہتا ہے مشکل کام کو آسان فرما دیتا ہے۔",
    audioUrl: "https://everydayduas.com/audio/dua_study.mp3",
    fallbackText: "اللهم لا سهل إلا ما جعلته سهلا وأنت تجعل الحزن إذا شئت سهلا",
    iconEmoji: "✍️",
    sectionType: "dua"
  }
];

export const HADITH_AUDIO_TRACKS: AudioTrack[] = [
  {
    id: "hadith_smile",
    titleEn: "Smiling is Charity",
    titleUr: "مسکرانا صدقہ ہے",
    categoryEn: "Kids Hadith",
    categoryUr: "بچوں کی احادیث",
    arabicText: "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ",
    transliteration: "Tabassumuka fii wajhi akhiika laka sadaqah",
    translationEn: "Your smiling in the face of your brother is charity for you.",
    translationUr: "تمہارا اپنے بھائی کے سامنے مسکرانا تمہارے لیے صدقہ ہے۔",
    referenceEn: "Sunan al-Tirmidhi (Sahih)",
    referenceUr: "سنن ترمذی (صحیح)",
    moralLessonEn: "Smiling makes other people happy and spreads love! Allah gives you reward just for sharing a beautiful smile. 😊",
    moralLessonUr: "مسکرانے سے محبت پھیلتی ہے اور اللہ تعالیٰ محض ایک خوبصورت مسکراہٹ پر بھی صدقے جتنا ثواب عطا کرتا ہے۔",
    audioUrl: "https://everydayduas.com/audio/hadith_smile.mp3",
    fallbackText: "تبسمك في وجه أخيك لك صدقة",
    iconEmoji: "😊",
    sectionType: "hadith"
  },
  {
    id: "hadith_kindness",
    titleEn: "Kindness Beautifies Everything",
    titleUr: "نرمی ہر چیز کو خوبصورت بناتی ہے",
    categoryEn: "Kids Hadith",
    categoryUr: "بچوں کی احادیث",
    arabicText: "إِنَّ الرِّفْقَ لَا يَكُونُ فِي شَيْءٍ إِلَّا زَانَهُ",
    transliteration: "Innar-rifqa laa yakuunu fii shai'in illaa zaanah",
    translationEn: "Indeed, kindness is not found in anything except that it beautifies it.",
    translationUr: "بیشک نرمی جس چیز میں بھی ہوتی ہے اسے خوبصورت بنا دیتی ہے۔",
    referenceEn: "Sahih Muslim",
    referenceUr: "صحیح مسلم",
    moralLessonEn: "Being gentle and kind to your family, friends, pets, and toys makes everything beautiful. Never be harsh! 🌱",
    moralLessonUr: "اپنے خاندان، دوستوں اور جانوروں کے ساتھ نرم مزاجی سے پیش آنا ہر کام کو خوبصورت بنا دیتا ہے۔",
    audioUrl: "https://everydayduas.com/audio/hadith_kindness.mp3",
    fallbackText: "إن الرفق لا يكون في شيء إلا زانه",
    iconEmoji: "🌸",
    sectionType: "hadith"
  },
  {
    id: "hadith_clean",
    titleEn: "Cleanliness is Half of Faith",
    titleUr: "صفائی نصف ایمان ہے",
    categoryEn: "Kids Hadith",
    categoryUr: "بچوں کی احادیث",
    arabicText: "الطَّهُورُ شَطْرُ الإِيمَانِ",
    transliteration: "At-tahooru shatrul-iimaan",
    translationEn: "Cleanliness is half of faith.",
    translationUr: "صفائی اور پاکیزگی نصف ایمان ہے۔",
    referenceEn: "Sahih Muslim",
    referenceUr: "صحیح مسلم",
    moralLessonEn: "Keeping your body clean, washing hands, brushing teeth, and keeping your room tidy is a big part of being a good Muslim! 🧼",
    moralLessonUr: "اپنے جسم کو پاک صاف رکھنا، اپنے کمرے کی صفائی کرنا ہمارے خوبصورت ایمان کا حصہ ہے۔",
    audioUrl: "https://everydayduas.com/audio/hadith_clean.mp3",
    fallbackText: "الطهور شطر الإيمان",
    iconEmoji: "🧼",
    sectionType: "hadith"
  },
  {
    id: "hadith_brotherhood",
    titleEn: "Love for Others What You Love for Yourself",
    titleUr: "دوسروں کے لیے وہی پسند کرو جو اپنے لیے پسند کرتے ہو",
    categoryEn: "Kids Hadith",
    categoryUr: "بچوں کی احادیث",
    arabicText: "لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ",
    transliteration: "Laa yu'minu ahadukum hatta yuhibba li-akhiihi maa yuhibbu li-nafsih",
    translationEn: "None of you truly believes until he loves for his brother what he loves for himself.",
    translationUr: "تم میں سے کوئی مومن نہیں ہو سکتا جب تک اپنے بھائی کے لیے وہی پسند نہ کرے جو اپنے لیے پسند کرتا ہے۔",
    referenceEn: "Sahih al-Bukhari & Muslim",
    referenceUr: "صحیح بخاری و مسلم",
    moralLessonEn: "Share your toys, treats, and joy with others! Treating friends the way you want to be treated brings immense rewards.",
    moralLessonUr: "اپنے کھلونا، کھانسی اور خوشیاں دوسروں کے ساتھ بانٹیں! جس طرح آپ اپنے لیے بھلائی چاہتے ہیں، دوسروں کے لیے بھی وہی چاہیں۔",
    audioUrl: "https://everydayduas.com/audio/hadith_brother.mp3",
    fallbackText: "لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه",
    iconEmoji: "🤝",
    sectionType: "hadith"
  },
  {
    id: "hadith_best_quran",
    titleEn: "The Best Among You Learn the Quran",
    titleUr: "تم میں سے بہترین وہ ہے جو قرآن سیکھے",
    categoryEn: "Kids Hadith",
    categoryUr: "بچوں کی احادیث",
    arabicText: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ",
    transliteration: "Khairukum man ta'allamal-Qur'ana wa 'allamah",
    translationEn: "The best among you are those who learn the Quran and teach it.",
    translationUr: "تم میں سے بہترین شخص وہ ہے جو قرآن سیکھے اور سکھائے۔",
    referenceEn: "Sahih al-Bukhari",
    referenceUr: "صحیح بخاری",
    moralLessonEn: "Reading and understanding the Holy Quran fills your heart with light and makes you beloved to Allah! 📖",
    moralLessonUr: "قرآن مجید کی تلاوت اور اس کی تعلیم سے دل نور سے بھر جاتا ہے اور انسان اللہ کا محبوب بنتا ہے۔",
    audioUrl: "https://everydayduas.com/audio/hadith_quran.mp3",
    fallbackText: "خيركم من تعلم القرآن وعلمه",
    iconEmoji: "📖",
    sectionType: "hadith"
  },
  {
    id: "hadith_truth",
    titleEn: "Truthfulness Leads to Goodness",
    titleUr: "سچائی بھلائی کی طرف لے جاتی ہے",
    categoryEn: "Kids Hadith",
    categoryUr: "بچوں کی احادیث",
    arabicText: "إِنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرِّ",
    transliteration: "Innas-sidqa yahdii ilal-birr",
    translationEn: "Truthfulness leads to righteousness, and righteousness leads to Paradise.",
    translationUr: "بیشک سچائی بھلائی اور نیکی کی طرف لے جاتی ہے اور نیکی جنت کا راستہ ہے۔",
    referenceEn: "Sahih al-Bukhari",
    referenceUr: "صحیح بخاری",
    moralLessonEn: "Always speak the truth, even when it's hard! Truthful children are trusted and loved by Allah and everyone. 🌟",
    moralLessonUr: "ہمیشہ سچ بولیں! سچے بچے اللہ تعالی کے محبوب ہوتے ہیں اور دنیا میں بھی عزت پاتے ہیں۔",
    audioUrl: "https://everydayduas.com/audio/hadith_truth.mp3",
    fallbackText: "إن الصدق يهدي إلى البر",
    iconEmoji: "🌟",
    sectionType: "hadith"
  },
  {
    id: "hadith_anger",
    titleEn: "Control Your Anger",
    titleUr: "غصہ نہ کرو",
    categoryEn: "Kids Hadith",
    categoryUr: "بچوں کی احادیث",
    arabicText: "لَا تَغْضَبْ وَلَكَ الْجَنَّةُ",
    transliteration: "Laa taghdab wa lakal-Jannah",
    translationEn: "Do not get angry, and for you is Paradise.",
    translationUr: "غصہ نہ کرو، تمہارے لیے جنت ہے۔",
    referenceEn: "Al-Mu'jam al-Awsat",
    referenceUr: "المعجم اوسط",
    moralLessonEn: "When you feel mad, take deep breaths, say Audhubillah, drink water, and stay calm! 🕊️",
    moralLessonUr: "جب غصہ آئے تو اعوذ باللہ پڑھیں، پانی پیئیں اور خاموش رہ کر اپنے آپ کو قابو میں رکھیں۔",
    audioUrl: "https://everydayduas.com/audio/hadith_anger.mp3",
    fallbackText: "لا تغضب ولك الجنة",
    iconEmoji: "🕊️",
    sectionType: "hadith"
  },
  {
    id: "hadith_parents",
    titleEn: "Pleasure of Allah in Parents",
    titleUr: "رب کی رضا والدین کی رضا میں ہے",
    categoryEn: "Kids Hadith",
    categoryUr: "بچوں کی احادیث",
    arabicText: "رِضَا الرَّبِّ فِي رِضَا الْوَالِدَيْنِ",
    transliteration: "Ridar-Rabbi fii ridal-walidayn",
    translationEn: "The pleasure of the Lord is in the pleasure of the parents.",
    translationUr: "رب کی رضا والدین کی رضا میں ہے۔",
    referenceEn: "Sunan al-Tirmidhi",
    referenceUr: "سنن ترمذی",
    moralLessonEn: "Obey and respect your parents! Making your parents happy pleases Allah Almighty. ❤️",
    moralLessonUr: "والدین کی خوشنودی سے اللہ تعالی راضی ہوتا ہے، اس لیے ہمیشہ ان کا احترام اور خدمت کریں۔",
    audioUrl: "https://everydayduas.com/audio/hadith_parents.mp3",
    fallbackText: "رضا الرب في رضا الوالدين",
    iconEmoji: "❤️",
    sectionType: "hadith"
  }
];
